version: '2.2'

volumes:
  geth-data:

services:
  ##
  # STELLAR CORE
  ##
  core:
    restart: always
    build: ./docker-stellar-core
    ports:
      - 11626
    volumes:
      - /mnt/data/otokarev/work/umbre/bifrost-provisioning/core:/data
      - ./volumes/core/configs:/configs
    environment:
      - NONEWHIST=1
      - DATABASE_URL="postgres://stellar:1q2w3e@core-db/core?sslmode=disable"
    links:
      - core-db
    depends_on:
      - core-db
  core-db:
    restart: always
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=1q2w3e
      - POSTGRES_DB=core
  ##
  # STELLAR HORIZON
  ##

  # horizon-init: Restart until exit with 0 status that means that DB schema loaded successfully
  horizon-init:
    restart: on-failure
    build: ./docker-stellar-horizon
    command:
      - db
      - init
    environment:
      - DATABASE_URL=postgres://stellar:1q2w3e@horizon-db/horizon?sslmode=disable
    depends_on:
      - horizon-db
  horizon:
    restart: always
    build: ./docker-stellar-horizon
    command:
      - --db-url=postgres://stellar:1q2w3e@horizon-db/horizon?sslmode=disable
      - --stellar-core-db-url=postgres://stellar:1q2w3e@core-db/core?sslmode=disable
      - --ingest=true
      - --stellar-core-url=http://core:11626
    ports:
      - 8031:8000
    links:
      - horizon-db
      - core
      - core-db
    depends_on:
      - horizon-init
      - core
  horizon-db:
    restart: always
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=1q2w3e
      - POSTGRES_DB=horizon
  ##
  # GETH
  #
  # seems it will not work if container resides in vbox
  # 'Fatal: Error starting protocol stack: sync /data/geth/chaindata: invalid argument'
  ##
  geth:
    restart: always
    image: ethereum/client-go
    # geth is too greedy. let's throttle it a bit
    cpus: 0.5
    mem_limit: '512m'
    command:
      - --rpc
      - --rpcaddr
      - 0.0.0.0
      - --rpccorsdomain
      - "*"
      - --rpcapi
      - "net,eth"
      - --testnet
      - --cache=512
      - --fast
      - --datadir
      - /data
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - geth-data:/data
  ##
  # BIFROST
  ##
  bifrost-init:
    restart: on-failure
    build: ./docker-stellar-bifrost
    command: ["init"]
    environment:
      BIFROST_DB_DSN: postgres://stellar:1q2w3e@bifrost-db/bifrost?sslmode=disable
  bifrost:
    restart: always
    build: ./docker-stellar-bifrost
    command: ["server"]
    environment:
      BIFROST_CFG: >
        {"ethereum": {"master_public_key": "xpub6C79eBsW2XQbzfXFsRv51Lac6Ckx5nyqf9cUmFr1fuAEHGXmpq8oPNMqCpH1jTdwP3s5SD644R8KK4cVytk9Jxcxcb7JsfNxcGNRbG5q4pq","network_id": "3","minimum_value_eth": "0.00001"},"stellar": {"token_asset_code": "TOKE","needs_authorize": "true","network_passphrase": "Test SDF Network ; September 2015"},"database": {"type": "postgres"}}
      BIFROST_ETHEREUM_RPC_SERVER: geth:8545
      BIFROST_STELLAR_ISSUER_PUBLIC_KEY: GD5H2WSHTWVTZI5BR3V5XTRBCFDMEOKFMXR4Y4PU337K7WS55UAADI5T
      BIFROST_STELLAR_SIGNER_SECRET_KEY: SD4DFZ433RUGNCMCG4JGWK47R5KOHQOS4T5LXGLGBLY7ZLBUZQTTONVQ
      BIFROST_STELLAR_HORIZON: http://horizon:8000
      BIFROST_DB_DSN: postgres://stellar:1q2w3e@bifrost-db/bifrost?sslmode=disable
    ports:
      - 8032:8000
    links:
      - bifrost-db
      - geth
      - horizon
    depends_on:
      - horizon
      - geth
      - bifrost-init
    volumes:
      - ./volumes/bifrost/configs:/configs
  bifrost-db:
    restart: always
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=1q2w3e
      - POSTGRES_DB=bifrost
  ##
  # BIFROST WEB APP
  ##
  bifrost-app:
    restart: always
    build: ./docker-stellar-bifrost-client
    ports:
      - 8030:3000
    depends_on:
      - bifrost
      - horizon
    environment:
      - HORIZON_URL=http://localhost:8031
      - BIFROST_URL=http://localhost:8032
      - ISSUING_ACCOUNT=GD5H2WSHTWVTZI5BR3V5XTRBCFDMEOKFMXR4Y4PU337K7WS55UAADI5T
      - NODE_ENV=development
      - ALLOW_HORIZON_HTTP=on
