version: '3'
services:
  ##
  # STELLAR CORE DB
  ##
  core-db:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=1q2w3e
      - POSTGRES_DB=core
  ##
  # STELLAR HORIZON DB
  ##
  horizon-db:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=1q2w3e
      - POSTGRES_DB=horizon
  ##
  # STELLAR CORE
  ##
  core:
    restart: always
    build: ./docker-stellar-core
    ports:
      - 11626
    volumes:
      - /mnt/data/otokarev/work/umbre/bifrost-provisioning/core:/data
      - ./volumes/core/configs:/configs
    environment:
      - NONEWHIST=1
      - DATABASE_URL="postgres://stellar:1q2w3e@core-db/core?sslmode=disable"
    links:
      - core-db
    depends_on:
      - core-db
  ##
  # STELLAR HORIZON INIT DB
  ##
  horizon-init:
    restart: on-failure
    build: ./docker-stellar-horizon
    command:
      - db
      - init
    environment:
      - DATABASE_URL=postgres://stellar:1q2w3e@horizon-db/horizon?sslmode=disable
    depends_on:
      - horizon-db
  ##
  # STELLAR HORIZON
  ##
  horizon:
    restart: always
    build: ./docker-stellar-horizon
    command:
      - --db-url=postgres://stellar:1q2w3e@horizon-db/horizon?sslmode=disable
      - --stellar-core-db-url=postgres://stellar:1q2w3e@core-db/core?sslmode=disable
      - --ingest=true
      - --stellar-core-url=http://core:11626
    ports:
      - 8000
    links:
      - horizon-db
      - core
      - core-db
    depends_on:
      - horizon-init
      - core
  ##
  # GETH
  #
  # seems it will not work if container resides in vbox
  # 'Fatal: Error starting protocol stack: sync /data/geth/chaindata: invalid argument'
  ##
  geth:
    restart: always
    image: ethereum/client-go
    command:
      - --rpc
      - --rpcaddr
      - 0.0.0.0
      - --rpccorsdomain
      - "*"
      - --rpcapi
      - "all"
      - --testnet
      - --cache=2048
      - --fast
      - --datadir
      - /data
    ports:
      - 8545
      - 30303:30303
    volumes:
      - ./volumes/geth/:/data
