- name: Delete Letsencrypt controller
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: deploy/letsencrypt.yaml.j2

- name: Delete Letsencript secrets
  shell: kubectl delete secret letsencrypt-service-credentials
  ignore_errors: yes
  when: force_secrets_drop is defined
