- name: Get k8s credentials from gcloud
  shell: gcloud config set project {{project}}
- name: Set namespace `{{namespace}}`
  shell: kubectl config set-context $(kubectl config current-context) --namespace={{namespace}}
