- name: Delete geth lb static IP
  shell: gcloud compute addresses delete -q {{namespace}}-geth-lb-ip --region={{region}}
  ignore_errors: yes
  when: force_ips_drop is defined

- name: Delete geth service
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: svc/geth.yaml.j2
    geth_lb_ip: "127.0.0.1" #dummy value to make template work

- name: Delete geth controller
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: sts/geth.yaml.j2
    geth_lb_ip: "127.0.0.1" #dummy value to make template work

- name: Drop volumes
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: pv/geth.yaml.j2

- name: Drop volume claims
  shell: kubectl delete pvc/geth-data-geth-{{item.0}}
  ignore_errors: yes
  with_indexed_items: "{{zones}}"

- name: Drop disks
  shell: |
    until gcloud compute disks delete -q {{namespace}}-geth-{{item}} --zone {{item}}; do : ; done;
  ignore_errors: yes
  with_items: "{{zones}}"
  async: 15
  poll: 3
  when: force_disks_drop is defined
