- name: Drop SQL instance
  shell: gcloud sql instances delete -q {{stellar_bifrost_sql_instance_id}}
  ignore_errors: yes
  when: stellar_bifrost_sql_instance_id is defined

- name: Delete bifrost lb static IP
  shell: gcloud compute addresses delete -q {{namespace}}-stellar-bifrost-lb-ip --global
  ignore_errors: yes
  when: force_ips_drop is defined

- name: Delete bifrost secrets
  shell: kubectl delete secret {{item}}
  ignore_errors: yes
  with_items:
    - 'cloudsql-instance-credentials'
    - 'stellar-bifrost-credentials'
  when: force_secrets_drop is defined

- name: Delete bifrost service
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: svc/bifrost.yaml.j2
    stellar_bifrost_domain_name: '' #dummy value to make template work

- name: Delete bifrost controller
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: sts/bifrost.yaml.j2
    stellar_lb_ip: '127.0.0.1' #dummy value to make template work

- name: Delete bifrost ingress
  include_tasks: utils/kubectl-delete.yaml
  vars:
    template: ing/bifrost.yaml.j2


