- name: Create cluster
  shell: >
    gcloud container clusters create {{cluster_name}}
    --cluster-version=1.7.15-gke.0
    --no-enable-cloud-logging
    --enable-cloud-monitoring
    --no-enable-cloud-endpoints
    --num-nodes=1
    --machine-type={{machine_type}}
    --zone={{zones[0]}} {% if zones[1] is defined %} --additional-zones={{zones[1]}} {% endif %}
  ignore_errors: yes

- name: Deploy namespaces
  include_tasks: utils/kubectl-create.yaml
  vars:
    template: ns/namespaces.yaml.j2

- name: Load credentials
  include_tasks: tasks/init.yml
- name: Deploy secret with nginx proxy template
  shell: >
    kubectl create secret generic nginx-proxy-cfg-template \
    --from-file={{nginx_proxy_cfg_template_path}}
  ignore_errors: yes
