  - name: Parse `{{template}}`
    template:
      src: "{{template}}"
      dest: ./cache/{{template|regex_replace('\.j2$')}}
  - name: Deploy {{template|regex_replace('\.yaml\.j2$')}}
    shell: kubectl create -f ./cache/{{template|regex_replace('\.j2$')}}
    ignore_errors: yes
