- name: Deploy all
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    additional_zones:

  tasks:
  ###
  # SQL INSTANCE
  ##
  - name: Install/Configure SQL instance
    include_tasks: utils/deploy-sql.yaml
    when: stellar_bifrost_sql_instance_id is defined
  ##
  # K8S CLUSTER
  ##
  - name: Create cluster
    shell: >
      gcloud container clusters create {{cluster_name}}
      --no-enable-cloud-logging
      --enable-cloud-monitoring
      --no-enable-cloud-endpoints
      --num-nodes=1
      --machine-type={{machine_type}}
      --zone={{zones[0]}} --additional-zones={{zones[1]}}
    ignore_errors: yes
  - name: Get k8s credentials from gcloud
    shell: gcloud container clusters get-credentials {{cluster_name}} --zone {{zones[0]}} --project {{project}}
  - name: Set namespace `{{namespace}}`
    shell: kubectl config set-context $(kubectl config current-context) --namespace={{namespace}}

  - name: Deploy namespaces
    include_tasks: utils/kubectl-create.yaml
    vars:
      template: ns/namespaces.yaml.j2

  ##
  # BALANCER IPS
  ##
  - name: Deploy Stellar lb static IP
    shell: gcloud compute addresses create {{namespace}}-stellar-lb-ip --region={{region}}
    ignore_errors: yes
  - name: Set stellar_lb_ip
    shell: gcloud compute addresses list | grep {{namespace}}-stellar-lb-ip | gawk '{print $3}'
    register: output
  - set_fact:
      stellar_lb_ip: "{{output.stdout_lines[0]}}"

  - name: Deploy Bifrost lb static IP
    shell: gcloud compute addresses create {{namespace}}-stellar-bifrost-lb-ip --region={{region}}
    ignore_errors: yes
  - name: Set stellar_lb_ip
    shell: gcloud compute addresses list | grep {{namespace}}-stellar-bifrost-lb-ip | gawk '{print $3}'
    register: output
  - set_fact:
      bifrost_lb_ip: "{{output.stdout_lines[0]}}"

  ##
  # DISKS & PERSISTENT VOLUMES(CLASSES)
  ##
  - name: Create disks
    shell: |
      gcloud compute disks create {{namespace}}-geth-{{item}} --size {{geth_storage_capacity_gb}}GB --type pd-standard --zone {{item}}
      gcloud compute disks create {{namespace}}-stellar-{{item}} --size {{stellar_storage_capacity_gb}}GB --type pd-standard --zone {{item}}
    ignore_errors: yes
    with_items: "{{zones}}"

  - name: Deploy volumes
    include_tasks: utils/kubectl-create.yaml
    vars:
      template: pv/volumes.yaml.j2

  ##
  # Deploy GETH
  ##
  - name: Deploy geth service
    include_tasks: utils/kubectl-create.yaml
    vars:
      template: svc/geth.yaml.j2
  - name: Deploy geth controller
    include_tasks: utils/kubectl-create-or-replace.yaml
    vars:
      controller_kind: sts
      controller_name: geth

  ##
  # Deploy STELLAR
  ##
  - name: Deploy secret with Stellar Core configuration file
    shell: kubectl create secret generic stellar-core-cfg --from-file=stellar-core.cfg={{stellar_core_cfg_path}}
    ignore_errors: yes

  - name: Deploy secret with Horizon Proxy SSL credentials and nginx config
    shell: >
      kubectl create secret generic stellar-horizon-proxy-secret \
      --from-file={{stellar_horizon_ssl_crt_path}} \
      --from-file={{stellar_horizon_ssl_key_path}} \
      --from-file={{stellar_horizon_proxy_cfg_template_path}}
    ignore_errors: yes

  - name: Deploy stellar service
    include_tasks: utils/kubectl-create.yaml
    vars:
      template: svc/stellar.yaml.j2
  - name: Deploy stellar controller
    include_tasks: utils/kubectl-create-or-replace.yaml
    vars:
      controller_kind: sts
      controller_name: stellar

  ##
  # Deploy BIFROST
  ##
  - name: Deploy secret with database client credentials
    shell: kubectl create secret generic cloudsql-instance-credentials --from-file=credentials.json={{stellar_bifrost_sql_client_key_path}}
    ignore_errors: yes
  - name: Deploy secret with Bifrost credentials
    shell: >
      kubectl create secret generic stellar-bifrost-credentials
      --from-literal=STELLAR_BIFROST_CFG='{{stellar_bifrost_cfg|to_json}}'
      --from-literal=STELLAR_BIFROST_DATABASE_URL="{{stellar_bifrost_database_url}}"
    ignore_errors: yes

  - name: Deploy bifrost service
    include_tasks: utils/kubectl-create.yaml
    vars:
      template: svc/bifrost.yaml.j2
  - name: Deploy bifrost controller
    include_tasks: utils/kubectl-create-or-replace.yaml
    vars:
      controller_kind: sts
      controller_name: bifrost

