- name: Deploy Geth
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    additional_zones:

  tasks:
  - name: Load credentials
    include_tasks: tasks/init.yml
  - name: Deploy Geth
    include_tasks: tasks/geth/create.yml
