- name: Deploy Stellar
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    additional_zones:

  tasks:
  - name: Load credentials
    include_tasks: tasks/init.yml
  - name: Deploy Stellar
    include_tasks: tasks/stellar/create.yml
