- name: Deploy Letsencrypt service
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    additional_zones:

  tasks:
  - name: Load credentials
    include_tasks: tasks/init.yml
  - name: Deploy Ingress
    include_tasks: tasks/ingress/create.yml
