- name: Clean all
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  tasks:
  - name: Drop bifrost
    include_tasks: tasks/bifrost/drop.yml
  - name: Drop stellar
    include_tasks: tasks/stellar/drop.yml
  - name: Drop geth
    include_tasks: tasks/geth/drop.yml

