- name: Clean all
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  tasks:
  - name: Drop SQL instance
    shell: gcloud sql instances delete {{stellar_bifrost_sql_instance_id}}
    ignore_errors: yes
    when: stellar_bifrost_sql_instance_id is defined
  - name: Drop cluster
    shell: gcloud container clusters delete {{cluster_name}} --zone={{zones[0]}} --quiet
    ignore_errors: yes
  - name: Drop static IPs
    shell: gcloud compute addresses delete {{item}} --region={{region}}
    ignore_errors: yes
    with_items:
    - "{{namespace}}-stellar-bifrost-lb-ip"
    - "{{namespace}}-stellar-lb-ip"
  - name: Drop disks
    shell: |
      gcloud compute disks delete {{namespace}}-geth-{{item}} --zone {{item}}
      gcloud compute disks delete {{namespace}}-stellar-{{item}} --zone {{item}}
    ignore_errors: yes
    with_items: "{{zones}}"
  #- name: Drop balancers
  #  shell: gcloud compute forwarding-rules list | gawk 'NR>1 {print $1}' | xargs gcloud compute forwarding-rules delete --region {{region}}
  #  ignore_errors: yes

