- name: Deploy all
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    configs:
      - stellar-0
      - stellar-1
    a: q

  tasks:
  - set_fact: a="{% for item in configs %} hui {% endfor %}"
  - debug: var=a
  - set_fact: version="{{configs}}"
  - debug: var=version


